### ISSUE TITLE
Icons are not rendering correctly

### ISSUE THREAD

**Issue by itsemon245** [mskelton/termicons.nvim#34]
![image](https://github.com/mskelton/termicons.nvim/assets/82655944/38b58047-0b47-4e0f-a479-4a9b166edf68)

I was wondering do I need a specific font for the icons to be loaded.

**Comment by mskelton** [comment]
As the name of the plugin implies, it requires [termicons](https://github.com/mskelton/termicons) as listed in the requirements section of the readme.

**Comment by itsemon245** [comment]
Yes, I have installed the font and it works in my kitty terminal.
However instead of just linking the web url into requirements it would be better if it's included as a dedicated step for installation in the docs.

Also I have noticed something, in gnome-terminal when I tying to change the font termicons is not listed in the font list although it is listed in the system font selection. I wonder why.

**Comment by mskelton** [comment]
@bdemon245 I'd rather not maintain the install instructions across two repos, thus the link to the source termicons repo.

I don't use linux, so sadly I'm not much help for you with gnome-terminal. If you figure it out, definitely let me know!
